services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: comma
      MARIADB_USER: comma_user
      MARIADB_PASSWORD: comma_password
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      CLIENT_URL: http://localhost:4000
      DB_NAME: comma
      DB_USER: comma_user
      DB_PASSWORD: comma_password
      DB_PORT: 3306
      DB_URL: db
      JWT_AUDIENCE: comma-users
      JWT_EXPIRES_IN: 7
      JWT_ISSUER: comma
      JWT_SECRET: super_secret_key_change_me
      PROXY_API_KEY: lezoWjkSU70HHrwNxRW9zSMW69tvtdJAIycw09i00oQrJaPVfNA4hjACDKeQSV2JMIwWuB0UVfWw1OhOjufQQ7QXJu3PPt2A5PtC97RZy1N0RZt4wQBVoNRMfxHbsKge
      PROXY_URL: https://proxy.hkayrad.me
      SERVER_PORT: 3001
      TOTP_ENCRYPTION_KEY: a9f16c032a8f8635ddb812ac54fd250279b1f9a16df02fb2d2a16825aeda28e9
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "3001:3001"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_API_URL: http://localhost:3001
        VITE_WEBSOCKET_URL: ws://localhost:3001/notification
        VITE_ENV: production
    ports:
      - "4000:80"
    depends_on:
      - server

volumes:
  db_data:
